# fly.toml app configuration file generated for fontbracket on 2025-05-07T16:16:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fontbracket'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
